# Generated by Django 4.1 on 2023-04-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0002_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="file_name",
            field=models.FileField(
                blank=True, max_length=254, null=True, upload_to=None
            ),
        ),
    ]
